name: Blue-Green Deployment

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Blue App
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/blue-app:latest ./app_blue

      - name: Build Green App
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/green-app:latest ./app_green

      - name: Push Blue App
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/blue-app:latest

      - name: Push Green App
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/green-app:latest
